### ISSUE TITLE
General App Use

### ISSUE THREAD

**Issue by MoritzRueff** [MoritzRueff/Capstone#1]
As a user, i want to use the app to look for available dogs to adopt.

## Description
![Screenshot 2022-01-10 at 12 20 39](https://user-images.githubusercontent.com/93935623/148758877-a9485e77-15ca-4454-b513-743b3162bb82.png)

## Complexity
S

## Acceptance Criteria
- header & footer visible
- basic form of App visible

## Tasks

- [x] create header
- [x] create footer
- [x] create all pages
- [x] create routes to all pages
- [x] create database for dogs
