### ISSUE TITLE
Display all available dogs

### ISSUE THREAD

**Issue by MoritzRueff** [MoritzRueff/Capstone#2]
## Value statement
I want to be able to see all available dogs

## Description
![Screenshot 2022-01-10 at 12 20 39](https://user-images.githubusercontent.com/93935623/148758717-f7d4485d-4251-43f2-9b74-5dff00be0f7e.png)

## Complexity
L

## Acceptance Criteria
- Some example dogs are added to a database
- Some of the dogs are shown in the App (randomly)

## Tasks

- [x]  create a database for the dogs
- [x] make dogs visible in app
- [x] show random dogs at Homepage
